version: '3.8'
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      target: production
      args:
        - NODE_ENV=${NODE_ENV}
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"